logging:
  pattern:
    console: log@%clr(%d{mm:ss SSS}){blue}%clr(-%5p){red} [%logger] %clr(%m){magenta}%n
  level:
    com.lan: debug
    org.springframework: WARN
    org.hibernate: WARN

spring:
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
      enabled: true
  profiles:
    active: dev
  cache:
    jcache:
      config: classpath:ehcache.xml

#port
server:
  port: 8081
mybatis:
  mapper-locations: classpath:com/lan/**/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true







